---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/about":
    get:
      summary: show info about the application
      tags:
      - About
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                required:
                - name
                - version
                properties:
                  name:
                    type: string
                  version:
                    type: string
servers:
- url: http://localhost:3000
  description: Localhost
